# ============================================================
# 010_quality_dashboard_visualization_tests.R
# Biomedical Quality Dashboard Verification App
# PostgreSQL + R + Shiny
# ============================================================
#
# PURPOSE:
# Interactive verification interface for the metrics generated by
# 09_quality_metrics_backend.R.
#
# This script is designed to help verify that dashboard metrics
# are being calculated correctly by comparing:
#
#   raw database table  ->  intermediate calculation  ->  final metric
#
# IMPORTANT:
# - This script does not modify the database.
# - This script does not insert data.
# - This script does not delete data.
# - This script only reads data and displays verification tables.
# - It is not the final production Shiny app.
# - It is a backend validation and debugging interface.
#
# ACADEMIC FRAMING:
#
# Completeness:
# Measures null values and populated field ratios.
#
# Consistency:
# Measures internal coherence using derived checks such as BMI
# plausibility and available internal consistency metrics.
#
# Accuracy:
# True clinical accuracy requires an external gold standard.
# This app only explores proxy accuracy through validation flags,
# plausibility checks, and statistical outlier detection.
#
# This app does not claim overdose detection, toxic dose detection,
# true diagnostic correctness, or pharmacological safety.
#
# ============================================================

# ------------------------------------------------------------
# Load Required Libraries
# ------------------------------------------------------------

library(DBI)
library(RPostgres)
library(tidyverse)
library(stringr)
library(lubridate)
library(uuid)
library(glue)
library(janitor)
library(ggplot2)
library(shiny)

# ------------------------------------------------------------
# Source Metrics Backend
# ------------------------------------------------------------

source("09_quality_metrics_backend.R")

# ------------------------------------------------------------
# Load Dashboard Context Safely
# ------------------------------------------------------------

load_context_for_app <- function() {

  con <- NULL

  tryCatch({

    con <- connect_db()

    context <- load_dashboard_context(con)

    dashboard_metrics <- generate_dashboard_metrics(context)

    list(
      context = context,
      dashboard_metrics = dashboard_metrics,
      loaded_at = Sys.time(),
      success = TRUE,
      error_message = NA_character_
    )

  }, error = function(e) {

    list(
      context = NULL,
      dashboard_metrics = NULL,
      loaded_at = Sys.time(),
      success = FALSE,
      error_message = e$message
    )

  }, finally = {

    if (!is.null(con)) {

      tryCatch({

        dbDisconnect(con)

      }, error = function(e) {

        message("Connection closing warning in load_context_for_app().")
      })
    }
  })
}

# ------------------------------------------------------------
# Helper: Metric Value Extractor
# ------------------------------------------------------------

get_metric_value <- function(metric_table, metric_name) {

  if (is.null(metric_table) || nrow(metric_table) == 0) {
    return(NA_real_)
  }

  value <- metric_table %>%
    filter(.data$metric_name == !!metric_name) %>%
    pull(.data$metric_value)

  if (length(value) == 0) {
    return(NA_real_)
  }

  return(value[[1]])
}

# ------------------------------------------------------------
# Helper: Manual Missingness Calculation
# ------------------------------------------------------------

manual_missingness_by_variable <- function(context) {

  patients <- context$patients
  fields <- get_evaluated_fields(context)

  if (nrow(patients) == 0 || length(fields) == 0) {

    return(tibble(
      variable_name = character(),
      manual_missing_count = numeric(),
      manual_non_missing_count = numeric(),
      manual_total_records = numeric(),
      manual_missing_percentage = numeric()
    ))
  }

  result <- tibble()

  for (field in fields) {

    values <- patients[[field]]

    if (is.character(values)) {

      missing_count <- sum(is.na(values) | str_trim(values) == "")

    } else {

      missing_count <- sum(is.na(values))
    }

    total_records <- nrow(patients)
    non_missing_count <- total_records - missing_count

    result <- bind_rows(
      result,
      tibble(
        variable_name = field,
        manual_missing_count = missing_count,
        manual_non_missing_count = non_missing_count,
        manual_total_records = total_records,
        manual_missing_percentage = round(
          safe_divide(missing_count, total_records) * 100,
          2
        )
      )
    )
  }

  result %>%
    arrange(desc(.data$manual_missing_percentage), .data$variable_name)
}

# ------------------------------------------------------------
# Helper: Completeness Verification Table
# ------------------------------------------------------------

build_completeness_verification_table <- function(context, dashboard_metrics) {

  backend_table <- dashboard_metrics$missingness_by_variable

  manual_table <- manual_missingness_by_variable(context)

  comparison <- backend_table %>%
    left_join(
      manual_table,
      by = "variable_name"
    ) %>%
    mutate(
      missing_count_match = .data$missing_count == .data$manual_missing_count,
      missing_percentage_match = abs(.data$missing_percentage - .data$manual_missing_percentage) < 0.01
    )

  return(comparison)
}

# ------------------------------------------------------------
# Helper: Manual Record Completeness
# ------------------------------------------------------------

manual_record_completeness <- function(context, selected_patient_id) {

  patients <- context$patients
  fields <- get_evaluated_fields(context)

  patient_row <- patients %>%
    filter(.data$patient_id == !!selected_patient_id)

  if (nrow(patient_row) == 0 || length(fields) == 0) {

    return(tibble(
      variable_name = character(),
      raw_value = character(),
      is_missing = logical()
    ))
  }

  result <- tibble()

  for (field in fields) {

    value <- patient_row[[field]][[1]]

    missing <- if (is.character(value)) {

      is.na(value) || str_trim(value) == ""

    } else {

      is.na(value)
    }

    result <- bind_rows(
      result,
      tibble(
        variable_name = field,
        raw_value = as.character(value),
        is_missing = missing
      )
    )
  }

  result
}

# ------------------------------------------------------------
# Helper: BMI Verification Table
# ------------------------------------------------------------

build_bmi_verification_table <- function(context, dashboard_metrics) {

  patients <- context$patients

  manual_bmi <- patients %>%
    transmute(
      patient_uuid,
      patient_id,
      raw_weight_kg = as.numeric(weight_kg),
      raw_height_cm = as.numeric(height_cm),
      manual_height_m = raw_height_cm / 100,
      manual_bmi = round(raw_weight_kg / (manual_height_m ^ 2), 2),
      manual_bmi = ifelse(
        is.na(raw_weight_kg) |
          is.na(raw_height_cm) |
          raw_height_cm <= 0,
        NA_real_,
        manual_bmi
      )
    )

  dashboard_metrics$bmi_table %>%
    left_join(
      manual_bmi,
      by = c("patient_uuid", "patient_id")
    ) %>%
    mutate(
      bmi_match = case_when(
        is.na(.data$bmi) & is.na(.data$manual_bmi) ~ TRUE,
        abs(.data$bmi - .data$manual_bmi) < 0.01 ~ TRUE,
        TRUE ~ FALSE
      )
    ) %>%
    arrange(.data$patient_id)
}

# ------------------------------------------------------------
# Helper: Dose per Kg Verification Table
# ------------------------------------------------------------

build_dose_per_kg_verification_table <- function(context) {

  patients <- context$patients

  patients %>%
    transmute(
      patient_uuid,
      patient_id,
      dosage_mg = as.numeric(dosage_mg),
      weight_kg = as.numeric(weight_kg),
      manual_dose_per_kg = round(dosage_mg / weight_kg, 4),
      manual_dose_per_kg = ifelse(
        is.na(dosage_mg) |
          is.na(weight_kg) |
          weight_kg <= 0,
        NA_real_,
        manual_dose_per_kg
      )
    ) %>%
    arrange(.data$patient_id)
}

# ------------------------------------------------------------
# Helper: Flag Burden Verification
# ------------------------------------------------------------

build_flag_burden_verification_table <- function(context, dashboard_metrics) {

  patients <- context$patients
  flags <- context$quality_flags

  manual_flag_counts <- flags %>%
    filter(!is.na(.data$patient_uuid)) %>%
    group_by(.data$patient_uuid) %>%
    summarise(
      manual_total_flags = n(),
      manual_warning_flags = sum(.data$severity == "WARNING", na.rm = TRUE),
      manual_critical_flags = sum(.data$severity == "CRITICAL", na.rm = TRUE),
      manual_info_flags = sum(.data$severity == "INFO", na.rm = TRUE),
      .groups = "drop"
    )

  patients %>%
    select(patient_uuid, patient_id) %>%
    left_join(
      dashboard_metrics$flag_burden_per_patient,
      by = c("patient_uuid", "patient_id")
    ) %>%
    left_join(
      manual_flag_counts,
      by = "patient_uuid"
    ) %>%
    mutate(
      manual_total_flags = replace_na(.data$manual_total_flags, 0),
      manual_warning_flags = replace_na(.data$manual_warning_flags, 0),
      manual_critical_flags = replace_na(.data$manual_critical_flags, 0),
      manual_info_flags = replace_na(.data$manual_info_flags, 0),
      total_flags_match = .data$total_flags == .data$manual_total_flags,
      warning_flags_match = .data$warning_flags == .data$manual_warning_flags,
      critical_flags_match = .data$critical_flags == .data$manual_critical_flags,
      info_flags_match = .data$info_flags == .data$manual_info_flags
    ) %>%
    arrange(desc(.data$total_flags), .data$patient_id)
}

# ------------------------------------------------------------
# Helper: Outlier Verification Table
# ------------------------------------------------------------

build_zscore_verification_table <- function(context, variable_name = "bmi") {

  detect_zscore_outliers(
    context = context,
    variable_name = variable_name,
    threshold = 3
  )
}

# ------------------------------------------------------------
# Initial Data Load
# ------------------------------------------------------------

initial_load <- load_context_for_app()

# ============================================================
# UI
# ============================================================

ui <- fluidPage(

  titlePanel("Biomedical Data Quality Metrics Verification App"),

  sidebarLayout(

    sidebarPanel(

      h4("Controls"),

      actionButton(
        inputId = "refresh_data",
        label = "Refresh data from PostgreSQL"
      ),

      br(),
      br(),

      uiOutput("patient_selector_ui"),

      br(),

      selectInput(
        inputId = "zscore_variable",
        label = "Z-score variable to inspect",
        choices = c(
          "age",
          "weight_kg",
          "height_cm",
          "dosage_mg",
          "bmi",
          "dose_per_kg"
        ),
        selected = "bmi"
      ),

      br(),

      helpText(
        "This app compares raw database values with backend metric calculations."
      ),

      helpText(
        "It does not insert, update, or delete any data."
      )
    ),

    mainPanel(

      tabsetPanel(

        tabPanel(
          "1. Overview",

          h3("Backend Load Status"),
          verbatimTextOutput("load_status"),

          h3("Completeness Summary"),
          tableOutput("completeness_summary"),

          h3("Flag Burden Summary"),
          tableOutput("flag_burden_summary"),

          h3("Hot/Cold Ratio"),
          tableOutput("hot_cold_ratio")
        ),

        tabPanel(
          "2. Raw Patients Table",

          h3("Raw public.patients Preview"),
          p("This is the real table loaded from PostgreSQL. Use it to compare raw values against the calculated metrics."),
          tableOutput("patients_preview"),

          h3("Patients Schema Preview"),
          tableOutput("patients_schema")
        ),

        tabPanel(
          "3. Completeness Verification",

          h3("Variable-level Missingness: Backend vs Manual Calculation"),
          p("This table compares the backend missingness calculation with an independent manual recalculation."),
          tableOutput("completeness_verification"),

          h3("Missingness by Variable Plot"),
          plotOutput("missingness_plot", height = "450px")
        ),

        tabPanel(
          "4. Patient-level Completeness",

          h3("Selected Patient Raw Completeness Check"),
          p("This shows every evaluated field for one selected patient and whether it is considered missing."),
          tableOutput("selected_patient_missingness"),

          h3("Backend Record Completeness for Selected Patient"),
          tableOutput("selected_patient_backend_completeness"),

          h3("Record Completeness Distribution"),
          plotOutput("record_completeness_plot", height = "400px")
        ),

        tabPanel(
          "5. BMI Verification",

          h3("BMI Calculation Verification"),
          p("This compares BMI calculated by the backend with a manual BMI recalculation from raw weight and height."),
          tableOutput("bmi_verification"),

          h3("BMI Category Distribution"),
          plotOutput("bmi_category_plot", height = "400px")
        ),

        tabPanel(
          "6. Dose per Kg / Statistical Dosage Anomaly",

          h3("Weight-normalized Dosage Table"),
          p("This is not overdose detection. It is only a statistical dosage anomaly check based on dosage_mg / weight_kg."),
          tableOutput("dose_per_kg_table"),

          h3("Z-score Outliers for Selected Variable"),
          tableOutput("zscore_outliers"),

          h3("Z-score Outlier Plot"),
          plotOutput("zscore_plot", height = "400px")
        ),

        tabPanel(
          "7. Flags Verification",

          h3("Raw quality_flags Table"),
          p("These are the stored quality flags from the database."),
          tableOutput("quality_flags_preview"),

          h3("Flag Burden: Backend vs Manual Count"),
          p("This compares backend flag burden metrics with a manual recount from quality_flags."),
          tableOutput("flag_burden_verification"),

          h3("Most Problematic Variables"),
          plotOutput("problematic_variables_plot", height = "450px")
        ),

        tabPanel(
          "8. Confidence Score",

          h3("Record Confidence Score"),
          p("Score starts at 100 and subtracts penalties for missing fields, warnings, critical flags, BMI implausibility, and statistical dosage anomalies."),
          tableOutput("confidence_score_table"),

          h3("Confidence Score Distribution"),
          plotOutput("confidence_score_plot", height = "400px")
        ),

        tabPanel(
          "9. Interpretation Notes",

          h3("How to Read This App"),

          tags$ul(
            tags$li("Completeness checks whether values are missing or populated."),
            tags$li("The variable-level completeness tab compares backend values with an independent manual recalculation."),
            tags$li("The patient-level tab allows you to inspect one patient field by field."),
            tags$li("BMI is recalculated manually from weight_kg and height_cm to verify the backend BMI."),
            tags$li("Dose per kg is only a statistical weight-normalized dosage anomaly measure."),
            tags$li("Quality flags are compared against manual counts from public.quality_flags."),
            tags$li("No data are modified by this app.")
          ),

          h3("Important Academic Limitation"),

          p(
            "True clinical accuracy cannot be measured without an external gold standard. ",
            "This system only measures proxy accuracy using validation-rule failures, ",
            "clinical plausibility checks, and statistical outlier detection."
          ),

          p(
            "The system should not be interpreted as detecting overdose, toxic dose, ",
            "diagnostic correctness, or pharmacological safety."
          )
        )
      )
    )
  )
)

# ============================================================
# SERVER
# ============================================================

server <- function(input, output, session) {

  app_data <- reactiveVal(initial_load)

  observeEvent(input$refresh_data, {

    refreshed <- load_context_for_app()

    app_data(refreshed)
  })

  context_reactive <- reactive({

    data <- app_data()

    validate(
      need(isTRUE(data$success), data$error_message)
    )

    data$context
  })

  metrics_reactive <- reactive({

    data <- app_data()

    validate(
      need(isTRUE(data$success), data$error_message)
    )

    data$dashboard_metrics
  })

  output$load_status <- renderPrint({

    data <- app_data()

    list(
      success = data$success,
      loaded_at = data$loaded_at,
      error_message = data$error_message,
      n_patients = if (!is.null(data$context)) nrow(data$context$patients) else NA,
      n_quality_flags = if (!is.null(data$context)) nrow(data$context$quality_flags) else NA,
      n_rejected_submissions = if (!is.null(data$context)) nrow(data$context$rejected_patient_submissions) else NA
    )
  })

  output$patient_selector_ui <- renderUI({

    context <- context_reactive()

    patient_choices <- context$patients %>%
      arrange(.data$patient_id) %>%
      pull(.data$patient_id)

    selectInput(
      inputId = "selected_patient_id",
      label = "Patient to inspect",
      choices = patient_choices,
      selected = patient_choices[[1]]
    )
  })

  # ----------------------------------------------------------
  # Overview Outputs
  # ----------------------------------------------------------

  output$completeness_summary <- renderTable({

    metrics_reactive()$completeness_summary
  })

  output$flag_burden_summary <- renderTable({

    metrics_reactive()$flag_burden_summary
  })

  output$hot_cold_ratio <- renderTable({

    metrics_reactive()$hot_cold_ratio
  })

  # ----------------------------------------------------------
  # Raw Patients Outputs
  # ----------------------------------------------------------

  output$patients_preview <- renderTable({

    context_reactive()$patients %>%
      arrange(.data$patient_id) %>%
      head(25)
  })

  output$patients_schema <- renderTable({

    context_reactive()$patients %>%
      summarise(across(everything(), ~class(.)[[1]])) %>%
      pivot_longer(
        cols = everything(),
        names_to = "column_name",
        values_to = "r_class"
      )
  })

  # ----------------------------------------------------------
  # Completeness Verification
  # ----------------------------------------------------------

  output$completeness_verification <- renderTable({

    build_completeness_verification_table(
      context = context_reactive(),
      dashboard_metrics = metrics_reactive()
    )
  })

  output$missingness_plot <- renderPlot({

    plot_data <- metrics_reactive()$missingness_by_variable %>%
      arrange(desc(.data$missing_percentage)) %>%
      mutate(
        variable_name = factor(.data$variable_name, levels = .data$variable_name)
      )

    ggplot(
      plot_data,
      aes(x = variable_name, y = missing_percentage)
    ) +
      geom_col() +
      coord_flip() +
      labs(
        title = "Missingness by Variable",
        x = "Variable",
        y = "Missing Values (%)"
      ) +
      theme_minimal()
  })

  # ----------------------------------------------------------
  # Patient-level Completeness
  # ----------------------------------------------------------

  output$selected_patient_missingness <- renderTable({

    req(input$selected_patient_id)

    manual_record_completeness(
      context = context_reactive(),
      selected_patient_id = input$selected_patient_id
    )
  })

  output$selected_patient_backend_completeness <- renderTable({

    req(input$selected_patient_id)

    metrics_reactive()$missingness_by_patient %>%
      filter(.data$patient_id == input$selected_patient_id)
  })

  output$record_completeness_plot <- renderPlot({

    ggplot(
      metrics_reactive()$missingness_by_patient,
      aes(x = record_completeness_percentage)
    ) +
      geom_histogram(bins = 20) +
      coord_cartesian(xlim = c(0, 100)) +
      labs(
        title = "Record Completeness Distribution",
        x = "Record Completeness (%)",
        y = "Number of Patients"
      ) +
      theme_minimal()
  })

  # ----------------------------------------------------------
  # BMI Verification
  # ----------------------------------------------------------

  output$bmi_verification <- renderTable({

    build_bmi_verification_table(
      context = context_reactive(),
      dashboard_metrics = metrics_reactive()
    ) %>%
      arrange(.data$bmi_match, .data$patient_id) %>%
      head(50)
  })

  output$bmi_category_plot <- renderPlot({

    plot_data <- metrics_reactive()$bmi_table %>%
      count(.data$bmi_category, name = "n")

    ggplot(
      plot_data,
      aes(x = bmi_category, y = n)
    ) +
      geom_col() +
      labs(
        title = "BMI Category Distribution",
        x = "BMI Category",
        y = "Number of Patients"
      ) +
      theme_minimal()
  })

  # ----------------------------------------------------------
  # Dose per Kg / Z-score Verification
  # ----------------------------------------------------------

  output$dose_per_kg_table <- renderTable({

    build_dose_per_kg_verification_table(
      context = context_reactive()
    ) %>%
      arrange(desc(.data$manual_dose_per_kg)) %>%
      head(50)
  })

  output$zscore_outliers <- renderTable({

    build_zscore_verification_table(
      context = context_reactive(),
      variable_name = input$zscore_variable
    )
  })

  output$zscore_plot <- renderPlot({

    plot_data <- build_zscore_verification_table(
      context = context_reactive(),
      variable_name = input$zscore_variable
    )

    if (nrow(plot_data) == 0) {

      plot.new()
      text(
        x = 0.5,
        y = 0.5,
        labels = "No z-score outliers detected for selected variable."
      )

    } else {

      ggplot(
        plot_data,
        aes(x = patient_id, y = z_score)
      ) +
        geom_col() +
        coord_flip() +
        labs(
          title = glue("Z-score Outliers: {input$zscore_variable}"),
          x = "Patient ID",
          y = "Z-score"
        ) +
        theme_minimal()
    }
  })

  # ----------------------------------------------------------
  # Flags Verification
  # ----------------------------------------------------------

  output$quality_flags_preview <- renderTable({

    context_reactive()$quality_flags %>%
      arrange(desc(.data$created_at)) %>%
      head(50)
  })

  output$flag_burden_verification <- renderTable({

    build_flag_burden_verification_table(
      context = context_reactive(),
      dashboard_metrics = metrics_reactive()
    ) %>%
      filter(
        .data$total_flags > 0 |
          .data$manual_total_flags > 0
      ) %>%
      arrange(desc(.data$total_flags), .data$patient_id)
  })

  output$problematic_variables_plot <- renderPlot({

    plot_data <- metrics_reactive()$most_problematic_variables %>%
      arrange(desc(.data$total_flags)) %>%
      mutate(
        variable_name = factor(.data$variable_name, levels = .data$variable_name)
      )

    if (nrow(plot_data) == 0) {

      plot.new()
      text(
        x = 0.5,
        y = 0.5,
        labels = "No quality flags available."
      )

    } else {

      ggplot(
        plot_data,
        aes(x = variable_name, y = total_flags)
      ) +
        geom_col() +
        coord_flip() +
        labs(
          title = "Most Problematic Variables",
          x = "Variable",
          y = "Total Quality Flags"
        ) +
        theme_minimal()
    }
  })

  # ----------------------------------------------------------
  # Confidence Score
  # ----------------------------------------------------------

  output$confidence_score_table <- renderTable({

    metrics_reactive()$record_confidence_score %>%
      arrange(.data$confidence_score) %>%
      head(50)
  })

  output$confidence_score_plot <- renderPlot({

    ggplot(
      metrics_reactive()$record_confidence_score,
      aes(x = confidence_score)
    ) +
      geom_histogram(bins = 20) +
      coord_cartesian(xlim = c(0, 100)) +
      labs(
        title = "Record Confidence Score Distribution",
        x = "Confidence Score",
        y = "Number of Patients"
      ) +
      theme_minimal()
  })
}

# ============================================================
# Run App
# ============================================================

shinyApp(ui = ui, server = server)